name: Pre-commit

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: pre-commit-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"

      - name: Run pre-commit
        run: uvx pre-commit run --all-files
